W10
HdVsha/GitStudy1 pull request #12
Opened 2020-11-22 22:53 UTC by HdVsha

2020-11-24 19:06 UTC, alekseik1 requested changes
Отписал в комменты.

22/27

2020-11-24 19:06 UTC, alekseik1 commented on w10/threading_explained.md
> +Увеличение числа потоков не ускоряет работу таковых.
В питоне - да, не ускоряет. В других программах может и ускорить, если она разрешает запускать несколько своих потоков одновременно.

2020-11-24 19:06 UTC, alekseik1 commented on w10/problems.md
> +__Deadlock__ - явление, когда 2 процесса поочередно завладевают потоком друг друга и соответственно ждут.
Не совсем так. Процессы же не делят память и работают изолированно, как тогда они могут захватить потоки друг друга?

2020-11-24 19:06 UTC, alekseik1 commented on w10/problems.md
> +__Race condition__ - когда потоки в каком-то недетерминированном порядке завладевают управлением чего-либо общего и из-за этого плохо влияют на работу друг друга.
Близко, но хотелось бы уточнения. Обязательно ли завладевать управлением?

2020-11-24 19:06 UTC, alekseik1 commented on w10/dot_task_upd.py
> +        print(threaded_dot(array_of_vecs, thread))
Не совсем хорошо: здесь в учет пойдет время, требуемое на разбиение массива и старт треда, хотя мы хотели бы именно время расчетов померить. На результат это несильно должно повлиять, но тренд могло бы изменить

2020-11-24 19:06 UTC, alekseik1 commented on w10/synchronization_primitives.md
> +Тут на помощь приходят классы __Queue__ и __Pipe__. Первый работает по принципу __очереди__, отдавая управление по порядку. Второй
Нет, `Queue` и `Pipe` не являются примитивами синхронизации, т.к. они не занимаются решением вопросов, кто в каком порядке запускается. Их задача - обеспечить передачу данных между процессами.

А вот `Lock` является одним из примитивов синхронизации, т.к. помогает задать очередность между процессами. Синхронизация здесь понимается как правильность в порядке выполнения, а не знание данных друг друга.

2020-11-24 19:06 UTC, alekseik1 commented on w10/dot_task_multiproc.py
> +            print(processed_dot(array_of_vecs, processes))
У меня на графиках время выполнения росло с ростом числа процессов, хотя так не должно быть. 
Стоило начать замерять время выполнения после того, как процессы отправлены, чтобы максимально приблизиться к подсчету чистого времени выполнения.

Но можно и не править ничего и запустить на `1e7` в длине вектора. Будет ± то, что нужно

2020-11-24 19:06 UTC, alekseik1 commented on w10/d_t_m_Queue.py
> +    tmp_results = [pool.apply_async(q_dot, args=(subarray1, subarray2, q,))  # Only need what in [...]
Жду фикса, о котором рассказал на семинаре)

2020-12-04 19:57 UTC, HdVsha commented
Исправил все, кроме последнего файла, который, по сути, является комбинацией заданий с Pool и Queue. Отписал вам в тг.

2020-12-13 00:35 UTC, merged